const Buttons = [
  {
    name: "Clear Display Operator",
    label: "CLEAR",
    color: "#FFF",
    bgColor: "red",
  },
  {
    name: "Save To Memory Button",
    label: "MEM+",
    color: "rgba(84,103,112,.83)",
    bgColor: "blue",
  },
  {
    name: "Get Next Value To Memory Button",
    label: "MEM-",
    color: "rgba(84,103,112,.83)",
    bgColor: "blue",
  },
  {
    name: "Last Result",
    label: "PREV",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Delete Last Character Button",
    label: "⌫",
    color: "#FFF",
    bgColor: "red",
  },
  {
    name: "Sign Toggle Operator",
    label: "+ / -",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Percent Of Operator",
    label: "% of",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Division Operator",
    label: "÷",
    color: "#FFF",
    bgColor: "#F6872C",
  },
  {
    name: "Number One Button",
    label: "1",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Number Two Button",
    label: "2",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Number Three Button",
    label: "3",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Multiplication Operator",
    label: "X",
    color: "#FFF",
    bgColor: "#F6872C",
  },
  {
    name: "Number Four Button",
    label: "4",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Number Five Button",
    label: "5",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Number Six Button",
    label: "6",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Subtraction Operator",
    label: "-",
    color: "#FFF",
    bgColor: "#F6872C",
  },
  {
    name: "Number Seven Button",
    label: "7",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Number Eight Button",
    label: "8",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Number Nine Button",
    label: "9",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Addition Operator",
    label: "+",
    color: "#FFF",
    bgColor: "#F6872C",
  },
  {
    name: "Number 0 Button",
    label: "0",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
    rowSpan: 2,
  },
  {
    name: "Period Button",
    label: ".",
    color: "rgba(84,103,112,.83)",
    bgColor: "#DCDCDC",
  },
  {
    name: "Equal Operator",
    label: "=",
    color: "#FFF",
    bgColor: "#F6872C",
  },
]

export default Buttons;