export const whiteText = "#FFFFFF";
export const displayBGColor = "#918987";
export const memoryBarBGColor = "#918987";
export const resultsBarBGColor = "#918987"
export const displayColor = whiteText;
export const orangeOperatorColor = "#f5993b"
export const blueButtonColor = "#9dc2d4"
export const redOperatorColor = "#e0301e"
export const yellowOperatorColor = "#fffc9a"

export const buttons = [
         {
           name: "Clear Display Operator",
           label: "CLR",
           color: whiteText,
           bgColor: redOperatorColor,
           type: "clear-button",
         },
         {
           name: "Save To Memory Button",
           label: "MEM+",
           color: "rgba(84,103,112,.83)",
           bgColor: yellowOperatorColor,
           type: "yellow-operator-button",
         },
         {
           name: "Get Next Value To Memory Button",
           label: "MEM–",
           color: "rgba(84,103,112,.83)",
           bgColor: yellowOperatorColor,
           type: "yellow-operator-button",
         },
         {
           name: "Last Result",
           label: "PREV",
           color: "rgba(84,103,112,.83)",
           bgColor: yellowOperatorColor,
           type: "yellow-operator-button",
         },
         {
           name: "Delete Last Character Button",
           label: "⌫",
           color: whiteText,
           bgColor: redOperatorColor,
           type: "delete-button",
         },
         {
           name: "Sign Toggle Operator",
           label: "±",
           color: whiteText,
           bgColor: orangeOperatorColor,
           type: "orange-operator-button",
         },
         {
           name: "Percent Of Operator",
           label: "% of",
           color: whiteText,
           bgColor: orangeOperatorColor,
           type: "orange-operator-button",
         },
         {
           name: "Division Operator",
           label: "÷",
           color: "#FFF",
           bgColor: orangeOperatorColor,
           type: "orange-operator-button",
         },
         {
           name: "Number One Button",
           label: "1",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "1",
         },
         {
           name: "Number Two Button",
           label: "2",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "2",
         },
         {
           name: "Number Three Button",
           label: "3",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "3",
         },
         {
           name: "Multiplication Operator",
           label: "X",
           color: "#FFF",
           bgColor: orangeOperatorColor,
           type: "orange-operator-button",
         },
         {
           name: "Number Four Button",
           label: "4",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "4",
         },
         {
           name: "Number Five Button",
           label: "5",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "5",
         },
         {
           name: "Number Six Button",
           label: "6",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "6",
         },
         {
           name: "Subtraction Operator",
           label: "–",
           color: "#FFF",
           bgColor: orangeOperatorColor,
           type: "orange-operator-button",
         },
         {
           name: "Number Seven Button",
           label: "7",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "7",
         },
         {
           name: "Number Eight Button",
           label: "8",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "8",
         },
         {
           name: "Number Nine Button",
           label: "9",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: "9",
         },
         {
           name: "Addition Operator",
           label: "+",
           color: "#FFF",
           bgColor: orangeOperatorColor,
           type: "orange-operator-button",
         },
         {
           name: "Number 0 Button",
           label: "0",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           rowSpan: 2,
           value: "0",
         },
         {
           name: "Period Button",
           label: ".",
           color: "rgba(84,103,112,.83)",
           bgColor: blueButtonColor,
           type: "blue-button",
           value: '.'
         },
         {
           name: "Equal Operator",
           label: "=",
           color: "#FFF",
           bgColor: orangeOperatorColor,
           type: "orange-operator-button",
         },
       ]
